name: ar_location_viewer_example
description: Demonstrates how to use the ar_location_viewer plugin.

publish_to: "none"

environment:
  sdk: ^3.7.0

dependencies:
  ar_location_viewer: 
    path: ../

  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/centaurus_mall.jpg
    - assets/marriott_hotel.jpg
    - assets/museum.jpg
    - assets/pakistan_monument.webp
    - assets/pims_hospital.jpg